name: "Create issue - Clean stale models dbt"

on:
  workflow_dispatch:
  push:


jobs:
  stale-models-prod:
    name: "Create issue - Clean stale models"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    # environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: dbt-macro-invocation
      #   id: dbt-macro-invocation
      #   run: echo "result=some_output" >> "$GITHUB_OUTPUT"

      - name: Read models_delete.txt
        id: read-file
        run: |
          MESSAGE=$(cat models_delete.txt)
          echo "MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV: dev
          MESSAGE: ${{ env.MESSAGE }}
        with:
          filename: .github/ISSUE_DROP_TABLES_NOT_UPDATED.md
          assignees: numberpioso
          update_existing: false
