name: "Create issue - Clean stale models dbt"

on:
  workflow_dispatch:
  push:


jobs:
  stale-models-prod:
    name: "Create issue - Clean stale models"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    # environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: dbt-macro-invocation
      #   id: dbt-macro-invocation
      #   run: echo "result=some_output" >> "$GITHUB_OUTPUT"

      - uses: JasonEtco/create-an-issue@v2
        - uses: JasonEtco/create-an-issue@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ENV: dev
            MESSAGE: ${{ $(cat models_delete.txt) }}
          with:
            filename: .github/ISSUE_DROP_TABLES_NOT_UPDATED.md
            assignees: numberpioso
            update_existing: false
